venv2/test_py2_dj182/test4/booktest/urls.py
from django.conf.urls import url
import views

urlpatterns=[
    url(r'^$', views.index, name='index'),
    url(r'^(\d+)/(\d+)$', views.show, name='show'),

    url(r'^user1$', views.user1, name='user1'),
    url(r'^user2$', views.user2, name='user2'),

    url(r'^htmlTest$', views.htmlTest),

    url(r'^csrf1$', views.csrf1),
    url(r'^csrf2$', views.csrf2),

    url(r'verify_code$', views.verify_code),
    url(r'verify_test1$', views.verify_test1),
    url(r'verify_test2$', views.verify_test2),
]

venv2/test_py2_dj182/test4/test4/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('booktest.urls', namespace='booktest')),
]

venv2/test_py2_dj182/test4/booktest/models.py
from django.db import models

class BookInfo(models.Model):
    btitle=models.CharField(max_length=20)
    bpub_date=models.DateField(db_column='pub_date')
    bread=models.IntegerField()
    bcommet=models.IntegerField()
    isDelete=models.BooleanField()
    class Meta():
        db_table='bookinfo'


class HeroInfo(models.Model):
    hname=models.CharField(max_length=10)
    hgender=models.BooleanField()
    hcontent = models.CharField(max_length=1000)
    isDelete = models.BooleanField()
    book = models.ForeignKey('BookInfo')
    def showname(self):
        return self.hname

venv2/test_py2_dj182/test4/booktest/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse
from models import *


def index(request):
    # hero=HeroInfo.objects.get(pk=1)
    # context={'hero': hero}

    list=HeroInfo.objects.filter(isDelete=False)
    context={'list': list}
    return render(request, 'booktest/index.html', context)

def show(request, id, id2):
    context={'id': id}
    return render(request, 'booktest/show.html', context)

# 模板教科案例框架
def user1(request):
    context={'uname': '阿弥陀佛'}
    return render(request, 'booktest/user1.html', context)

def user2(request):
    return render(request, 'booktest/user2.html')

# HTML转义
def htmlTest(request):
    context={'list': '<h1>abc</h1>'}
    return render(request, 'booktest/htmlTest.html', context)

# csrf
def csrf1(request):
    return render(request, 'booktest/csrf1.html')

def csrf2(request):
    uname=request.POST['uname']
    return HttpResponse(uname)

# 验证码
def verify_code(request):
    from PIL import Image, ImageDraw, ImageFont
    import random
    # 创建背景色
    bgcolor=(random.randrange(50, 100), random.randrange(50, 100), 0)
    # 规定宽高
    width=100
    height=25
    # 创建画布
    image=Image.new('RGB', (width, height), bgcolor)
    # 构造字体对象
    font=ImageFont.truetype('FreeMono.ttf', 24)
    # 创建画笔
    draw=ImageDraw.Draw(image)
    # 创建文本内容
    text='0123abcd'

    # 逐个绘制8个字符
    # for i in range(4):
    #     draw.text((i*25, 0),
    #          text[random.randrange(0, len(text))],
    #          (255, 255, 255),
    #          font)

    # 4个字符的绘制
    # draw.text((0, 0), text, (255, 255, 255), font)

    # 将字符存入session
    textTmp=''
    for i in range(4):
        textTmp1=text[random.randrange(0, len(text))]
        textTmp+=textTmp1
        draw.text((i*25, 0),
                  textTmp1,
                  (255, 255, 255),
                  font)
        request.session['code']=textTmp

    # 保存到内存流中
    import cStringIO    # 内存操作的包
    buf=cStringIO.StringIO()
    image.save(buf, 'png')

    return HttpResponse(buf.getvalue(), 'image/png')

def verify_test1(request):
    return render(request, 'booktest/verify_test1.html')

def verify_test2(request):
    code1=request.POST['code1']
    code2=request.session['code']
    if code1==code2:
        return HttpResponse('ok')
    else:
        return HttpResponse('no')

venv2/test_py2_dj182/test4/templates/booktest/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% block head %}{% endblock %}
</head>
<body>
<h1>logo</h1>
<hr>
{% block content1 %}
    <h1>父模板预留区域，留坑</h1>
{% endblock %}
<hr>
<h1>contact {{ uname }}</h1>
</body>
</html>

venv2/test_py2_dj182/test4/templates/booktest/base_user.html
{% extends 'booktest/base.html' %}
{% block content1 %}
<table border="2">
    <tr>
        <td height="600">用<br>户<br>导<br>航</td>
        <td>{% block user_content %}{% endblock %}</td>
    </tr>
</table>
{% endblock content1 %}

venv2/test_py2_dj182/test4/templates/booktest/csrf1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="csrf2" method="post">
    {% csrf_token %}
    <input type="text" name="uname">
    <input type="submit" value="提交">
</form>
</body>
</html>

venv2/test_py2_dj182/test4/templates/booktest/htmlTest.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ list|safe }}
<hr>
{% autoescape off %}
{{ list }}
{% endautoescape %}
<hr>
字面值:<br>
{{ list2|default:'<h1>123</h1>'}}
<br>
手动转义:<br>
{{ list2|default:'&lt;h1&gt;123&lt;/h1&gt;' }}
</body>
</html>

venv2/test_py2_dj182/test4/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<a href='{% url "booktest:show" "456" "789" %}'>显示</a>
<hr>
{{ hero.showname }}
<hr>
{# 这是单行注释，底下commet是多行注释 #}
{% comment %}
http://blog.csdn/net/xyp84/article/details/7945094
{% endcomment %}
<ul>
    {% for hero in list%}
            {% if forloop.counter|divisibleby:"2" %}
                <li style="color:green">{{ forloop.counter }}{{ hero.showname }}</li>
            {% else %}
                <li style="color:blue">{{ forloop.counter }}{{ hero.showname }}</li>
            {% endif %}
        {% empty %}
        <li>nothing ...</li>
    {% endfor %}
</ul>
</body>
</html>

venv2/test_py2_dj182/test4/templates/booktest/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ id }}
</body>
</html>

venv2/test_py2_dj182/test4/templates/booktest/user1.html
{% extends 'booktest/base_user.html' %}
{% block head %}
    <script>alert('这是孙子模板越级填base爷爷模板的坑')</script>
{% endblock head %}
{% block user_content %}
    <h1>用户中心1</h1>
{% endblock user_content %}

venv2/test_py2_dj182/test4/templates/booktest/user2.html
{% extends 'booktest/base_user.html' %}
{% block user_content %}
    <h1>用户中心2</h1>
{% endblock user_content %}

venv2/test_py2_dj182/test4/templates/booktest/verify_test1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="verify_test2" method="post">
    {% csrf_token %}
    <input type="text" name="code1">
    <img src="verify_code">
    <input type="submit" value="提交">
</form>
</body>
</html>